workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.sabohub.app
      groups:
        - app_store # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
      vars:
        BUNDLE_ID: "com.sabohub.app"
        APP_NAME: "SABOHUB"
        # Environment variables from .env file
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        SUPABASE_SERVICE_ROLE_KEY: $SUPABASE_SERVICE_ROLE_KEY
        # Google Drive credentials (for documents feature)
        GOOGLE_DRIVE_CLIENT_ID_IOS: $GOOGLE_DRIVE_CLIENT_ID_IOS
        GOOGLE_DRIVE_CLIENT_ID_WEB: $GOOGLE_DRIVE_CLIENT_ID_WEB
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up .env file
        script: |
          #!/usr/bin/env bash
          
          cat <<EOF > .env
          SUPABASE_URL=$SUPABASE_URL
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
          GOOGLE_DRIVE_CLIENT_ID_IOS=$GOOGLE_DRIVE_CLIENT_ID_IOS
          GOOGLE_DRIVE_CLIENT_ID_WEB=$GOOGLE_DRIVE_CLIENT_ID_WEB
          GOOGLE_DRIVE_CLIENT_ID_ANDROID=$GOOGLE_DRIVE_CLIENT_ID_ANDROID
          EOF
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # submit_to_app_store: true # Uncomment to submit to App Store

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "com.sabohub.app"
        # Environment variables from .env file
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        SUPABASE_SERVICE_ROLE_KEY: $SUPABASE_SERVICE_ROLE_KEY
        # Google Drive credentials
        GOOGLE_DRIVE_CLIENT_ID_ANDROID: $GOOGLE_DRIVE_CLIENT_ID_ANDROID
        GOOGLE_DRIVE_CLIENT_ID_WEB: $GOOGLE_DRIVE_CLIENT_ID_WEB
      flutter: stable
      java: 17
    scripts:
      - name: Set up .env file
        script: |
          #!/usr/bin/env bash
          
          cat <<EOF > .env
          SUPABASE_URL=$SUPABASE_URL
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
          GOOGLE_DRIVE_CLIENT_ID_ANDROID=$GOOGLE_DRIVE_CLIENT_ID_ANDROID
          GOOGLE_DRIVE_CLIENT_ID_WEB=$GOOGLE_DRIVE_CLIENT_ID_WEB
          EOF
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      - name: Set up key.properties
        script: |
          cat <<EOF > $CM_BUILD_DIR/android/key.properties
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Build Android release
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
