import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/daily_work_report.dart';
import '../models/attendance.dart';
import '../utils/app_logger.dart';

/// Daily Work Report Service
/// Auto-generates work reports when employee checks out
class DailyWorkReportService {
  final SupabaseClient _supabase;
  
  DailyWorkReportService(this._supabase);

  /// Generate report from attendance data
  /// Called automatically when employee checks out
  Future<DailyWorkReport> generateReportFromCheckout({
    required AttendanceRecord attendance,
    required String userName,
    required String? companyId, // Add companyId parameter
    required String? userRole,  // Add userRole parameter
    List<TaskSummary>? completedTasks,
  }) async {
    // Simulate API processing delay
    await Future.delayed(const Duration(milliseconds: 500));

    // Calculate work hours
    final checkIn = attendance.checkInTime!;
    final checkOut = attendance.checkOutTime!;
    final totalHours = checkOut.difference(checkIn).inMinutes / 60.0;

    // Auto-collect task data
    final tasks =
        completedTasks ?? await _collectTodayCompletedTasks(attendance.employeeId);

    // Generate summary based on work data
    final autoSummary = _generateWorkSummary(
      totalHours: totalHours,
      tasksCompleted: tasks.length,
      tasks: tasks,
    );

    // Create report draft
    final report = DailyWorkReport(
      id: 'report_${DateTime.now().millisecondsSinceEpoch}',
      userId: attendance.employeeId,
      userName: userName,
      branchId: attendance.companyId,
      date: attendance.date,
      checkInTime: checkIn,
      checkOutTime: checkOut,
      totalHours: totalHours,
      tasksCompleted: tasks.length,
      tasksAssigned: tasks.length, // TODO: Get from task service
      completedTasks: tasks,
      autoGeneratedSummary: autoSummary,
      status: ReportStatus.draft,
      createdAt: DateTime.now(),
    );

    // Save to Supabase
    try {
      await _saveReportToDatabase(report, companyId, userRole);
      AppLogger.api('Report saved to database: ${report.id}');
    } catch (e) {
      AppLogger.error('Failed to save report to database', e);
    }

    return report;
  }
  
  /// Save report to Supabase daily_work_reports table
  Future<void> _saveReportToDatabase(
    DailyWorkReport report,
    String? companyId,
    String? userRole,
  ) async {
    final data = {
      'employee_id': report.userId,  // Changed from user_id to employee_id
      'company_id': companyId ?? '', // From user
      'branch_id': report.branchId,
      'report_date': report.date.toIso8601String().split('T')[0], // YYYY-MM-DD
      'check_in_time': report.checkInTime.toIso8601String(),
      'check_out_time': report.checkOutTime.toIso8601String(),
      'total_hours': report.totalHours,
      'tasks_summary': _formatTasksSummary(report.completedTasks),
      'achievements': report.achievements?.join('\n'),
      'challenges': report.challenges?.join('\n'),
      'notes': report.employeeNotes,
      'employee_name': report.userName,
      'employee_role': userRole ?? 'STAFF',
    };

    await _supabase.from('daily_work_reports').insert(data);
  }
  
  /// Format tasks into summary text
  String _formatTasksSummary(List<TaskSummary> tasks) {
    if (tasks.isEmpty) return 'Không có công việc được ghi nhận';
    
    final buffer = StringBuffer();
    for (var i = 0; i < tasks.length; i++) {
      final task = tasks[i];
      buffer.writeln('${i + 1}. ${task.taskTitle}');
      if (task.taskDescription != null) {
        buffer.writeln('   ${task.taskDescription}');
      }
      if (task.notes != null) {
        buffer.writeln('   → ${task.notes}');
      }
    }
    return buffer.toString();
  }

  /// Auto-collect completed tasks from today's shift
  Future<List<TaskSummary>> _collectTodayCompletedTasks(String userId) async {
    try {
      final today = DateTime.now();
      final todayStr = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
      
      final response = await _supabase
          .from('management_tasks')
          .select('id, title, description, completed_at, notes')
          .eq('assigned_to', userId)
          .eq('status', 'completed')
          .gte('completed_at', '${todayStr}T00:00:00')
          .lte('completed_at', '${todayStr}T23:59:59')
          .limit(50);
      
      return (response as List).map((json) {
        return TaskSummary(
          taskId: json['id'] as String? ?? '',
          taskTitle: json['title'] as String? ?? 'Công việc',
          taskDescription: json['description'] as String?,
          completedAt: json['completed_at'] != null
              ? DateTime.tryParse(json['completed_at'] as String) ?? DateTime.now()
              : DateTime.now(),
          notes: json['notes'] as String?,
        );
      }).toList();
    } catch (e) {
      AppLogger.error('Error fetching tasks', e);
      return [];
    }
  }

  /// Generate AI-powered work summary
  String _generateWorkSummary({
    required double totalHours,
    required int tasksCompleted,
    required List<TaskSummary> tasks,
  }) {
    final buffer = StringBuffer();

    // Summary header
    buffer.writeln('📊 Tóm tắt ca làm việc:');
    buffer.writeln('');

    // Work hours
    buffer
        .writeln('⏰ Thời gian làm việc: ${totalHours.toStringAsFixed(1)} giờ');
    buffer.writeln('✅ Hoàn thành: $tasksCompleted công việc');
    buffer.writeln('');

    // Task details
    if (tasks.isNotEmpty) {
      buffer.writeln('📝 Chi tiết công việc:');
      for (var i = 0; i < tasks.length; i++) {
        final task = tasks[i];
        buffer.writeln('${i + 1}. ${task.taskTitle}');
        if (task.notes != null) {
          buffer.writeln('   → ${task.notes}');
        }
      }
      buffer.writeln('');
    }

    // Performance evaluation
    final performance = _evaluatePerformance(totalHours, tasksCompleted);
    buffer.writeln('🎯 Đánh giá: $performance');

    return buffer.toString();
  }

  /// Evaluate work performance
  String _evaluatePerformance(double totalHours, int tasksCompleted) {
    if (totalHours >= 8 && tasksCompleted >= 3) {
      return 'Xuất sắc - Làm việc chăm chỉ, hoàn thành nhiều công việc';
    } else if (totalHours >= 6 && tasksCompleted >= 2) {
      return 'Tốt - Đạt mục tiêu công việc';
    } else if (totalHours >= 4 && tasksCompleted >= 1) {
      return 'Trung bình - Cần cải thiện hiệu suất';
    } else {
      return 'Cần cố gắng thêm';
    }
  }

  /// Update report with employee notes
  Future<DailyWorkReport> updateReport({
    required String reportId,
    String? employeeNotes,
    List<String>? achievements,
    List<String>? challenges,
    String? tomorrowPlan,
  }) async {
    final updateData = <String, dynamic>{};
    if (employeeNotes != null) updateData['notes'] = employeeNotes;
    if (achievements != null) updateData['achievements'] = achievements.join('\n');
    if (challenges != null) updateData['challenges'] = challenges.join('\n');
    // tomorrowPlan can be stored in notes or a separate column
    
    if (updateData.isNotEmpty) {
      await _supabase.from('daily_work_reports').update(updateData).eq('id', reportId);
    }
    
    // Return the updated report
    final report = await getReport(reportId);
    if (report == null) throw Exception('Report not found');
    return report;
  }

  /// Submit report
  Future<DailyWorkReport> submitReport(String reportId) async {
    await _supabase.from('daily_work_reports').update({
      'status': 'submitted',
    }).eq('id', reportId);
    
    final report = await getReport(reportId);
    if (report == null) throw Exception('Report not found');
    return report;
  }

  /// Get report by ID
  Future<DailyWorkReport?> getReport(String reportId) async {
    try {
      final json = await _supabase
          .from('daily_work_reports')
          .select()
          .eq('id', reportId)
          .maybeSingle();
      if (json == null) return null;
      return _mapDbToReport(json);
    } catch (e) {
      AppLogger.error('Error fetching report', e);
      return null;
    }
  }

  /// Get all reports for user
  Future<List<DailyWorkReport>> getUserReports(String userId) async {
    try {
      final response = await _supabase
          .from('daily_work_reports')
          .select('*')
          .eq('employee_id', userId)
          .order('report_date', ascending: false)
          .limit(100);

      return (response as List).map((json) => _mapDbToReport(json)).toList();
    } catch (e) {
      AppLogger.error('Error fetching reports from database', e);
      return [];
    }
  }

  /// Parse tasks summary from database text format
  List<TaskSummary> _parseTasksSummary(String? summary) {
    if (summary == null || summary.isEmpty) return [];
    
    // Simple parsing - split by newlines and create task summaries
    final lines = summary.split('\n').where((line) => line.trim().isNotEmpty);
    return lines.map((line) {
      return TaskSummary(
        taskId: 'task_${line.hashCode}',
        taskTitle: line.replaceAll(RegExp(r'^[•\-\*]\s*'), '').trim(),
        completedAt: DateTime.now(), // Approximate
      );
    }).toList();
  }

  /// Get today's report for user (if exists)
  Future<DailyWorkReport?> getTodayReport(String userId) async {
    try {
      final today = DateTime.now();
      final todayStr = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
      
      final json = await _supabase
          .from('daily_work_reports')
          .select()
          .eq('employee_id', userId)
          .eq('report_date', todayStr)
          .maybeSingle();
      
      if (json == null) return null;
      return _mapDbToReport(json);
    } catch (e) {
      AppLogger.error('Error fetching today report', e);
      return null;
    }
  }

  /// Get all reports for branch (Manager view)
  Future<List<DailyWorkReport>> getBranchReports(String branchId) async {
    try {
      final response = await _supabase
          .from('daily_work_reports')
          .select('*')
          .eq('branch_id', branchId)
          .order('report_date', ascending: false)
          .limit(100);

      return (response as List).map((json) => _mapDbToReport(json)).toList();
    } catch (e) {
      AppLogger.error('Error fetching branch reports from database', e);
      return [];
    }
  }

  /// Get reports by date range
  Future<List<DailyWorkReport>> getReportsByDateRange({
    required String userId,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    try {
      final startStr = '${startDate.year}-${startDate.month.toString().padLeft(2, '0')}-${startDate.day.toString().padLeft(2, '0')}';
      final endStr = '${endDate.year}-${endDate.month.toString().padLeft(2, '0')}-${endDate.day.toString().padLeft(2, '0')}';
      
      final response = await _supabase
          .from('daily_work_reports')
          .select()
          .eq('employee_id', userId)
          .gte('report_date', startStr)
          .lte('report_date', endStr)
          .order('report_date', ascending: false)
          .limit(100);
      
      return (response as List).map((json) => _mapDbToReport(json)).toList();
    } catch (e) {
      AppLogger.error('Error fetching reports by date range', e);
      return [];
    }
  }

  /// Delete draft report
  Future<void> deleteDraftReport(String reportId) async {
    // Soft delete
    await _supabase.from('daily_work_reports').update({
      'is_active': false,
    }).eq('id', reportId);
  }

  /// Get statistics for manager view
  Future<Map<String, dynamic>> getReportStatistics({
    required String companyId,
    required DateTime date,
  }) async {
    try {
      final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
      
      final response = await _supabase
          .from('daily_work_reports')
          .select('id, total_hours, tasks_summary, status')
          .eq('company_id', companyId)
          .eq('report_date', dateStr)
          .limit(200);
      
      final dayReports = response as List;
      final totalReports = dayReports.length;
      final submittedReports = dayReports.where((r) => r['status'] == 'submitted').length;
      final avgHours = totalReports == 0
          ? 0.0
          : dayReports.map((r) => (r['total_hours'] as num?)?.toDouble() ?? 0.0).reduce((a, b) => a + b) / totalReports;
      
      return {
        'total_reports': totalReports,
        'submitted_reports': submittedReports,
        'pending_reports': totalReports - submittedReports,
        'average_hours': avgHours,
        'total_tasks_completed': totalReports, // Approximate
        'submission_rate': totalReports > 0 ? (submittedReports / totalReports * 100) : 0,
      };
    } catch (e) {
      AppLogger.error('Error fetching report statistics', e);
      return {
        'total_reports': 0,
        'submitted_reports': 0,
        'pending_reports': 0,
        'average_hours': 0.0,
        'total_tasks_completed': 0,
        'submission_rate': 0,
      };
    }
  }

  /// Get all reports for company on specific date (for Manager/CEO view)
  Future<List<DailyWorkReport>> getCompanyReports(
    String companyId,
    DateTime date,
  ) async {
    try {
      final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
      
      final response = await _supabase
          .from('daily_work_reports')
          .select()
          .eq('company_id', companyId)
          .eq('report_date', dateStr)
          .order('employee_name')
          .limit(200);
      
      return (response as List).map((json) => _mapDbToReport(json)).toList();
    } catch (e) {
      AppLogger.error('Error fetching company reports', e);
      return [];
    }
  }

  /// Map database row to DailyWorkReport
  DailyWorkReport _mapDbToReport(Map<String, dynamic> json) {
    return DailyWorkReport(
      id: json['id'] as String,
      userId: json['employee_id'] as String,
      userName: json['employee_name'] as String? ?? 'Nhân viên',
      branchId: json['branch_id'] as String?,
      date: DateTime.parse(json['report_date'] as String),
      checkInTime: DateTime.parse(json['check_in_time'] as String),
      checkOutTime: DateTime.parse(json['check_out_time'] as String),
      totalHours: (json['total_hours'] as num).toDouble(),
      tasksCompleted: 0,
      tasksAssigned: 0,
      completedTasks: _parseTasksSummary(json['tasks_summary'] as String?),
      autoGeneratedSummary: json['achievements'] as String? ?? '',
      employeeNotes: json['notes'] as String?,
      status: ReportStatus.submitted,
      createdAt: DateTime.parse(json['created_at'] as String),
      submittedAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
    );
  }
}

// Riverpod Providers
final dailyWorkReportServiceProvider = Provider<DailyWorkReportService>((ref) {
  return DailyWorkReportService(Supabase.instance.client);
});

/// Today's report for current user
final todayWorkReportProvider =
    FutureProvider.autoDispose.family<DailyWorkReport?, String>((ref, userId) async {
  final service = ref.watch(dailyWorkReportServiceProvider);
  return await service.getTodayReport(userId);
});

/// All reports for user
final userWorkReportsProvider =
    FutureProvider.autoDispose.family<List<DailyWorkReport>, String>((ref, userId) async {
  final service = ref.watch(dailyWorkReportServiceProvider);
  return await service.getUserReports(userId);
});

/// All reports for branch (Manager view)
final branchWorkReportsProvider =
    FutureProvider.autoDispose.family<List<DailyWorkReport>, String>((ref, branchId) async {
  final service = ref.watch(dailyWorkReportServiceProvider);
  return await service.getBranchReports(branchId);
});

/// Report statistics for manager
final reportStatisticsProvider =
    FutureProvider.autoDispose.family<Map<String, dynamic>, Map<String, dynamic>>(
        (ref, params) async {
  final service = ref.watch(dailyWorkReportServiceProvider);
  return await service.getReportStatistics(
    companyId: params['companyId'] as String,
    date: params['date'] as DateTime,
  );
});
