import 'dart:convert';

/// AI-generated daily plan: workout + meals + tips.
///
/// Stored as JSONB in Supabase `gym_daily_plans` table.
/// Generated by GymPlannerService via Gemini AI.
class DailyPlan {
  final String id;
  final DateTime planDate;
  final PlannedWorkout? workout;
  final List<PlannedMeal> meals;
  final String? dailyTip;
  final int targetCalories;
  final Map<String, int> targetMacros; // protein, carbs, fat in grams
  final bool isRestDay;
  final DateTime createdAt;

  const DailyPlan({
    required this.id,
    required this.planDate,
    this.workout,
    this.meals = const [],
    this.dailyTip,
    this.targetCalories = 2500,
    this.targetMacros = const {'protein': 150, 'carbs': 300, 'fat': 70},
    this.isRestDay = false,
    required this.createdAt,
  });

  factory DailyPlan.fromJson(Map<String, dynamic> json) {
    final workoutData = json['workout_plan'];
    final mealData = json['meal_plan'];

    Map<String, dynamic>? workoutMap;
    if (workoutData is String) {
      workoutMap = jsonDecode(workoutData) as Map<String, dynamic>?;
    } else if (workoutData is Map<String, dynamic>) {
      workoutMap = workoutData;
    }

    List<dynamic>? mealList;
    if (mealData is String) {
      mealList = jsonDecode(mealData) as List<dynamic>?;
    } else if (mealData is List) {
      mealList = mealData;
    }

    return DailyPlan(
      id: json['id'] as String? ?? '',
      planDate: DateTime.parse(json['plan_date'] as String),
      workout: workoutMap != null ? PlannedWorkout.fromJson(workoutMap) : null,
      meals: mealList
              ?.map((m) => PlannedMeal.fromJson(m as Map<String, dynamic>))
              .toList() ??
          const [],
      dailyTip: json['daily_tip'] as String?,
      targetCalories: json['target_calories'] as int? ?? 2500,
      targetMacros: (json['target_macros'] as Map<String, dynamic>?)
              ?.map((k, v) => MapEntry(k, (v as num).toInt())) ??
          const {'protein': 150, 'carbs': 300, 'fat': 70},
      isRestDay: json['is_rest_day'] as bool? ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toSupabaseRow(String userId) => {
        'user_id': userId,
        'plan_date': _dateStr(planDate),
        'workout_plan': workout?.toJson(),
        'meal_plan': meals.map((m) => m.toJson()).toList(),
        'daily_tip': dailyTip,
        'target_calories': targetCalories,
        'target_macros': targetMacros,
        'is_rest_day': isRestDay,
      };

  static String _dateStr(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';
}

/// AI-generated workout for the day.
class PlannedWorkout {
  final String name;
  final String type; // push, pull, legs, upper, lower, fullBody, cardio
  final int estimatedMinutes;
  final String? warmup;
  final List<PlannedExercise> exercises;
  final String? cooldown;

  const PlannedWorkout({
    required this.name,
    required this.type,
    this.estimatedMinutes = 60,
    this.warmup,
    this.exercises = const [],
    this.cooldown,
  });

  factory PlannedWorkout.fromJson(Map<String, dynamic> json) {
    return PlannedWorkout(
      name: json['name'] as String? ?? 'Workout',
      type: json['type'] as String? ?? 'custom',
      estimatedMinutes: json['estimated_minutes'] as int? ?? 60,
      warmup: json['warmup'] as String?,
      exercises: (json['exercises'] as List?)
              ?.map((e) => PlannedExercise.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      cooldown: json['cooldown'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'name': name,
        'type': type,
        'estimated_minutes': estimatedMinutes,
        'warmup': warmup,
        'exercises': exercises.map((e) => e.toJson()).toList(),
        'cooldown': cooldown,
      };

  int get totalSets => exercises.fold(0, (sum, e) => sum + e.sets);
}

/// A single exercise in a planned workout.
class PlannedExercise {
  final String name;
  final int sets;
  final String reps; // "8-12" or "10" or "30 sec"
  final String? weight; // "60kg" or "bodyweight" or null
  final int restSeconds;
  final String? notes;
  final int order;
  bool isCompleted;

  PlannedExercise({
    required this.name,
    this.sets = 3,
    this.reps = '10',
    this.weight,
    this.restSeconds = 90,
    this.notes,
    this.order = 0,
    this.isCompleted = false,
  });

  factory PlannedExercise.fromJson(Map<String, dynamic> json) {
    return PlannedExercise(
      name: json['name'] as String? ?? '',
      sets: json['sets'] as int? ?? 3,
      reps: json['reps']?.toString() ?? '10',
      weight: json['weight'] as String?,
      restSeconds: json['rest_seconds'] as int? ?? 90,
      notes: json['notes'] as String?,
      order: json['order'] as int? ?? 0,
    );
  }

  Map<String, dynamic> toJson() => {
        'name': name,
        'sets': sets,
        'reps': reps,
        'weight': weight,
        'rest_seconds': restSeconds,
        'notes': notes,
        'order': order,
      };
}

/// A meal in the daily nutrition plan.
class PlannedMeal {
  final String name; // "Bữa sáng", "Bữa trưa", etc.
  final String time; // "7:00", "12:00"
  final List<String> foods;
  final int calories;
  final Map<String, int> macros; // protein, carbs, fat
  bool isCompleted;

  PlannedMeal({
    required this.name,
    required this.time,
    this.foods = const [],
    this.calories = 0,
    this.macros = const {},
    this.isCompleted = false,
  });

  factory PlannedMeal.fromJson(Map<String, dynamic> json) {
    return PlannedMeal(
      name: json['name'] as String? ?? '',
      time: json['time'] as String? ?? '',
      foods: (json['foods'] as List?)?.map((f) => f.toString()).toList() ??
          const [],
      calories: json['calories'] as int? ?? 0,
      macros: (json['macros'] as Map<String, dynamic>?)
              ?.map((k, v) => MapEntry(k, (v as num).toInt())) ??
          const {},
    );
  }

  Map<String, dynamic> toJson() => {
        'name': name,
        'time': time,
        'foods': foods,
        'calories': calories,
        'macros': macros,
      };
}
