import 'package:flutter/material.dart';

/// Daily Work Report Model
/// Auto-generated when employee checks out
class DailyWorkReport {
  final String id;
  final String userId;
  final String userName;
  final String? companyId;
  final String? branchId;
  final DateTime date;
  final DateTime checkInTime;
  final DateTime checkOutTime;
  final double totalHours;

  // Auto-collected work data
  final int tasksCompleted;
  final int tasksAssigned;
  final List<TaskSummary> completedTasks;
  final String? autoGeneratedSummary;

  // Employee can edit these
  final String? employeeNotes;
  final List<String>? achievements;
  final List<String>? challenges;
  final String? tomorrowPlan;

  // Metadata
  final ReportStatus status;
  final DateTime createdAt;
  final DateTime? submittedAt;
  final DateTime? updatedAt;

  const DailyWorkReport({
    required this.id,
    required this.userId,
    required this.userName,
    this.companyId,
    this.branchId,
    required this.date,
    required this.checkInTime,
    required this.checkOutTime,
    required this.totalHours,
    this.tasksCompleted = 0,
    this.tasksAssigned = 0,
    this.completedTasks = const [],
    this.autoGeneratedSummary,
    this.employeeNotes,
    this.achievements,
    this.challenges,
    this.tomorrowPlan,
    this.status = ReportStatus.draft,
    required this.createdAt,
    this.submittedAt,
    this.updatedAt,
  });

  DailyWorkReport copyWith({
    String? id,
    String? userId,
    String? userName,
    String? companyId,
    String? branchId,
    DateTime? date,
    DateTime? checkInTime,
    DateTime? checkOutTime,
    double? totalHours,
    int? tasksCompleted,
    int? tasksAssigned,
    List<TaskSummary>? completedTasks,
    String? autoGeneratedSummary,
    String? employeeNotes,
    List<String>? achievements,
    List<String>? challenges,
    String? tomorrowPlan,
    ReportStatus? status,
    DateTime? createdAt,
    DateTime? submittedAt,
    DateTime? updatedAt,
  }) {
    return DailyWorkReport(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      userName: userName ?? this.userName,
      companyId: companyId ?? this.companyId,
      branchId: branchId ?? this.branchId,
      date: date ?? this.date,
      checkInTime: checkInTime ?? this.checkInTime,
      checkOutTime: checkOutTime ?? this.checkOutTime,
      totalHours: totalHours ?? this.totalHours,
      tasksCompleted: tasksCompleted ?? this.tasksCompleted,
      tasksAssigned: tasksAssigned ?? this.tasksAssigned,
      completedTasks: completedTasks ?? this.completedTasks,
      autoGeneratedSummary: autoGeneratedSummary ?? this.autoGeneratedSummary,
      employeeNotes: employeeNotes ?? this.employeeNotes,
      achievements: achievements ?? this.achievements,
      challenges: challenges ?? this.challenges,
      tomorrowPlan: tomorrowPlan ?? this.tomorrowPlan,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      submittedAt: submittedAt ?? this.submittedAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  factory DailyWorkReport.fromJson(Map<String, dynamic> json) {
    return DailyWorkReport(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      userName: json['user_name'] as String,
      companyId: json['company_id'] as String?,
      branchId: json['branch_id'] as String?,
      date: DateTime.parse(json['date'] as String),
      checkInTime: DateTime.parse(json['check_in_time'] as String),
      checkOutTime: DateTime.parse(json['check_out_time'] as String),
      totalHours: (json['total_hours'] as num).toDouble(),
      tasksCompleted: json['tasks_completed'] as int? ?? 0,
      tasksAssigned: json['tasks_assigned'] as int? ?? 0,
      completedTasks: (json['completed_tasks'] as List?)
              ?.map((e) => TaskSummary.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      autoGeneratedSummary: json['auto_generated_summary'] as String?,
      employeeNotes: json['employee_notes'] as String?,
      achievements: (json['achievements'] as List?)?.cast<String>(),
      challenges: (json['challenges'] as List?)?.cast<String>(),
      tomorrowPlan: json['tomorrow_plan'] as String?,
      status: ReportStatus.values.firstWhere(
        (s) => s.name == json['status'],
        orElse: () => ReportStatus.draft,
      ),
      createdAt: DateTime.parse(json['created_at'] as String),
      submittedAt: json['submitted_at'] != null
          ? DateTime.parse(json['submitted_at'] as String)
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'user_name': userName,
      'company_id': companyId,
      'branch_id': branchId,
      'date': date.toIso8601String(),
      'check_in_time': checkInTime.toIso8601String(),
      'check_out_time': checkOutTime.toIso8601String(),
      'total_hours': totalHours,
      'tasks_completed': tasksCompleted,
      'tasks_assigned': tasksAssigned,
      'completed_tasks': completedTasks.map((t) => t.toJson()).toList(),
      'auto_generated_summary': autoGeneratedSummary,
      'employee_notes': employeeNotes,
      'achievements': achievements,
      'challenges': challenges,
      'tomorrow_plan': tomorrowPlan,
      'status': status.name,
      'created_at': createdAt.toIso8601String(),
      'submitted_at': submittedAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }
}

/// Task Summary for Report
class TaskSummary {
  final String taskId;
  final String taskTitle;
  final String? taskDescription;
  final DateTime completedAt;
  final String? notes;

  const TaskSummary({
    required this.taskId,
    required this.taskTitle,
    this.taskDescription,
    required this.completedAt,
    this.notes,
  });

  factory TaskSummary.fromJson(Map<String, dynamic> json) {
    return TaskSummary(
      taskId: json['task_id'] as String,
      taskTitle: json['task_title'] as String,
      taskDescription: json['task_description'] as String?,
      completedAt: DateTime.parse(json['completed_at'] as String),
      notes: json['notes'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'task_id': taskId,
      'task_title': taskTitle,
      'task_description': taskDescription,
      'completed_at': completedAt.toIso8601String(),
      'notes': notes,
    };
  }
}

/// Report Status
enum ReportStatus {
  draft('Nháp', Color(0xFF9CA3AF)),
  submitted('Đã nộp', Color(0xFF10B981)),
  reviewed('Đã xem', Color(0xFF3B82F6)),
  approved('Đã duyệt', Color(0xFF8B5CF6));

  final String label;
  final Color color;
  const ReportStatus(this.label, this.color);
}
