-- ============================================
-- GYM DAILY PLANS — AI-generated workout + meal plans
-- ============================================
-- Stores daily plans generated by GymPlannerService (Gemini AI).
-- One plan per user per day. Workout + meals stored as JSONB.
-- ============================================

CREATE TABLE IF NOT EXISTS public.gym_daily_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_date DATE NOT NULL,
  workout_plan JSONB,
  meal_plan JSONB DEFAULT '[]'::jsonb,
  daily_tip TEXT,
  target_calories INTEGER DEFAULT 2500,
  target_macros JSONB DEFAULT '{"protein": 150, "carbs": 300, "fat": 70}'::jsonb,
  is_rest_day BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, plan_date)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_gym_daily_plans_user_date
  ON public.gym_daily_plans(user_id, plan_date DESC);

-- RLS
ALTER TABLE public.gym_daily_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY gym_daily_plans_own ON public.gym_daily_plans
  FOR ALL USING (auth.uid() = user_id);
